version: "3.8"

services:
  app:
    container_name: keypro-app
    build:
      context: .
      dockerfile: Dockerfile.develop
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: sh -c "npm i && npm run dev"
